'use client';
import Link from 'next/link';
import {useState} from 'react';
import {services} from './data';
export function Navigation(){const [open,setOpen]=useState(false);return <nav><div className="nav-inner"><Link className="logo" href="/" onClick={()=>setOpen(false)}><i/>oxygn</Link><div className={`nav-links ${open?'open':''}`}>{[['Services','/services'],['Platform','/platform'],['Trust','/trust'],['About','/about'],['Resources','/resources']].map(([x,h])=><Link key={x} href={h} onClick={()=>setOpen(false)}>{x}</Link>)}</div><Link className="btn primary nav-cta" href="/contact">Talk to us <span>↗</span></Link><button className="menu" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}><span/><span/></button></div></nav>}
export function Footer(){return <footer><div className="container footer-grid"><div><p className="logo">oxygn</p><p className="muted">AI-native governance, risk, and compliance for regulated financial institutions.</p><a className="muted" href="mailto:hello@oxygn.xyz">hello@oxygn.xyz</a></div><div><b>Services</b>{services.map(([x])=><Link key={x} href="/services">{x}</Link>)}</div><div><b>Company</b>{['Platform','Trust','About','Resources','Contact'].map(x=><Link key={x} href={`/${x.toLowerCase()}`}>{x}</Link>)}</div><div><b>Markets</b>{['Singapore (MAS)','ADGM (FSRA)','Hong Kong (SFC)','UK (FCA)','DIFC (DFSA)'].map(x=><span key={x}>{x}</span>)}</div></div><div className="container copyright">© 2026 Oxygn Pte Ltd. Singapore. oxygn.xyz</div></footer>}
export function Shell({children}:{children:React.ReactNode}){return <><Navigation/><main>{children}</main><Footer/></>}
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
export function CTA(){return <section className="section"><div className="container"><div className="cta-panel"><Eyebrow>Start here</Eyebrow><h2>Put your compliance function<br/>on auto-pilot.</h2><p>One conversation. A clear map of your obligations, operating model, and next step.</p><Link className="btn light" href="/contact">Request a working session <span>↗</span></Link></div></div></section>}
